// src/context/LanguageContext.jsx
import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    brand: '⚡ Proxify',
    browse: 'Browse',
    skillSwap: 'Skill Swap',
    post: '+ Post',
    profile: 'Profile',
    signIn: 'Sign In',
    logout: 'Logout',
    tagline: 'Find micro-jobs, swap skills, and connect with people in your neighborhood.',
    continueWithGoogle: 'Continue with Google',
    browseJobsTitle: '💼 Browse Jobs',
    browseJobsSubtitle: 'Find micro-jobs and tasks near you',
    skillSwapTitle: '🔄 Skill Swap',
    skillSwapSubtitle: 'Exchange skills with people in your city',
    all: 'All',
    urgentOnly: '🔴 Urgent Only',
    loadingJobs: 'Loading jobs...',
    noJobsFound: 'No jobs found. Try a different filter or be the first to post!',
    open: 'Open',
    urgent: '🔴 Urgent',
    plumbing: 'Plumbing', electrical: 'Electrical', music: 'Music',
    tutoring: 'Tutoring', delivery: 'Delivery', cleaning: 'Cleaning',
    carpentry: 'Carpentry', cooking: 'Cooking', other: 'Other',
    postJobTitle: 'Post a Job',
    postSkillSwapTitle: 'Post a Skill Swap',
    postJobSubtitle: 'Fill in the details — people nearby will see it instantly.',
    typeLabel: 'Type', jobTask: '💼 Job / Task', skillSwapType: '🔄 Skill Swap',
    titleLabel: 'Title',
    titlePlaceholderJob: 'e.g. Fix leaky kitchen tap',
    titlePlaceholderSkill: 'e.g. Guitar lessons for cooking lessons',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Describe the work in detail...',
    categoryLabel: 'Category', priceLabel: 'Price (₹)', pricePlaceholder: 'e.g. 500',
    dateLabel: 'Date', timeLabel: 'Time',
    areaLabel: 'Area / Locality', areaPlaceholder: 'e.g. Kozhikode Beach',
    cityLabel: 'City', cityPlaceholder: 'e.g. Kozhikode',
    contactPhoneLabel: 'Contact Phone (for WhatsApp)', contactPhonePlaceholder: 'e.g. 9876543210',
    urgentLabel: '🔴 Mark as Urgent', urgentDesc: 'Highlights your post — use only if time-critical',
    postNow: 'Post Now →', posting: 'Posting...',
    fillRequired: 'Please fill in all required fields.',
    postSuccess: 'Job posted successfully!', postError: 'Something went wrong. Try again.',
    postedBy: 'Posted By', description: 'Description', noReviews: 'No reviews yet',
    skills: 'Skills', contactWhatsapp: '💬 Contact on WhatsApp',
    expressInterest: '👋 Express Interest', interestExpressed: '✅ Interest Expressed',
    leaveReview: '⭐ Leave a Review', shareExperience: 'Share your experience...',
    submitReview: 'Submit Review', submitting: 'Submitting...',
    signInFirst: 'Please sign in first.',
    interestToast: 'Interest expressed! The poster will see your profile.',
    reviewSuccess: 'Review submitted!', reviewError: 'Failed to submit review.',
    reviews: 'reviews', interested: 'interested',
    jobNotFound: 'Job not found.', loading: 'Loading...',
    locationNotSet: '📍 Location not set',
    editProfile: '✏️ Edit', cancelEdit: 'Cancel',
    areaLocalityLabel: 'Area / Locality', phoneLabel: 'Phone (for WhatsApp contact)',
    skillsOfferedLabel: 'Skills I Offer (comma separated)',
    skillsOfferedPlaceholder: 'e.g. Plumbing, Guitar, Cooking',
    skillsNeededLabel: 'Skills I Want to Learn (comma separated)',
    skillsNeededPlaceholder: 'e.g. Driving, Tailoring',
    saveProfile: 'Save Profile', saving: 'Saving...',
    profileSaved: 'Profile updated!', profileError: 'Failed to save. Try again.',
    myPosts: 'My Posts', noPostsYet: "You haven't posted anything yet.",
    postAJob: 'Post a job →', loadingProfile: 'Loading profile...', needsLabel: 'needs:',
  },
  ml: {
    brand: '⚡ പ്രോക്സിഫൈ',
    browse: 'തൊഴിലുകൾ',
    skillSwap: 'നൈപുണ്യ വിനിമയം',
    post: '+ പോസ്റ്റ്',
    profile: 'പ്രൊഫൈൽ',
    signIn: 'സൈൻ ഇൻ',
    logout: 'ലോഗ്ഔട്ട്',
    tagline: 'നിങ്ങളുടെ അയൽപ്രദേശത്ത് ചെറുജോലികൾ കണ്ടെത്തുക, നൈപുണ്യം കൈമാറുക.',
    continueWithGoogle: 'Google വഴി തുടരുക',
    browseJobsTitle: '💼 തൊഴിലുകൾ കാണുക',
    browseJobsSubtitle: 'നിങ്ങൾക്ക് അടുത്തുള്ള ചെറുജോലികളും ടാസ്കുകളും കണ്ടെത്തുക',
    skillSwapTitle: '🔄 നൈപുണ്യ വിനിമയം',
    skillSwapSubtitle: 'നിങ്ങളുടെ നഗരത്തിലെ ആളുകളുമായി നൈപുണ്യം കൈമാറുക',
    all: 'എല്ലാം', urgentOnly: '🔴 അടിയന്തര മാത്രം',
    loadingJobs: 'ജോലികൾ ലോഡ് ചെയ്യുന്നു...',
    noJobsFound: 'ജോലികളൊന്നും കണ്ടെത്തിയില്ല. മറ്റൊരു ഫിൽറ്റർ പരീക്ഷിക്കുക!',
    open: 'തുറന്നത്', urgent: '🔴 അടിയന്തരം',
    plumbing: 'പ്ലംബിംഗ്', electrical: 'ഇലക്ട്രിക്കൽ', music: 'സംഗീതം',
    tutoring: 'ട്യൂഷൻ', delivery: 'ഡെലിവറി', cleaning: 'ക്ലീനിംഗ്',
    carpentry: 'തച്ചുപണി', cooking: 'പാചകം', other: 'മറ്റുള്ളവ',
    postJobTitle: 'ഒരു ജോലി പോസ്റ്റ് ചെയ്യുക',
    postSkillSwapTitle: 'നൈപുണ്യ വിനിമയം പോസ്റ്റ് ചെയ്യുക',
    postJobSubtitle: 'വിശദാംശങ്ങൾ പൂരിപ്പിക്കുക — അടുത്തുള്ളവർ ഉടൻ കാണും.',
    typeLabel: 'തരം', jobTask: '💼 ജോലി / ടാസ്ക്', skillSwapType: '🔄 നൈപുണ്യ വിനിമയം',
    titleLabel: 'തലക്കെട്ട്',
    titlePlaceholderJob: 'ഉദാ: അടുക്കളയിലെ ടാപ്പ് ശരിയാക്കുക',
    titlePlaceholderSkill: 'ഉദാ: ഗിറ്റാർ പഠിപ്പിക്കാം, പകരം പാചകം പഠിക്കണം',
    descriptionLabel: 'വിവരണം', descriptionPlaceholder: 'ജോലി വിശദമായി വിവരിക്കുക...',
    categoryLabel: 'വിഭാഗം', priceLabel: 'വില (₹)', pricePlaceholder: 'ഉദാ: 500',
    dateLabel: 'തീയതി', timeLabel: 'സമയം',
    areaLabel: 'പ്രദേശം / ലൊക്കാലിറ്റി', areaPlaceholder: 'ഉദാ: കോഴിക്കോട് ബീച്ച്',
    cityLabel: 'നഗരം', cityPlaceholder: 'ഉദാ: കോഴിക്കോട്',
    contactPhoneLabel: 'ബന്ധപ്പെടാനുള്ള ഫോൺ (WhatsApp-ന്)', contactPhonePlaceholder: 'ഉദാ: 9876543210',
    urgentLabel: '🔴 അടിയന്തരമായി അടയാളപ്പെടുത്തുക',
    urgentDesc: 'നിങ്ങളുടെ പോസ്റ്റ് ഹൈലൈറ്റ് ചെയ്യുന്നു — സമയ നിർണ്ണായകമെങ്കിൽ മാത്രം',
    postNow: 'ഇപ്പോൾ പോസ്റ്റ് ചെയ്യുക →', posting: 'പോസ്റ്റ് ചെയ്യുന്നു...',
    fillRequired: 'എല്ലാ നിർബന്ധ ഫീൽഡുകളും പൂരിപ്പിക്കുക.',
    postSuccess: 'ജോലി വിജയകരമായി പോസ്റ്റ് ചെയ്തു!', postError: 'തകരാർ സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.',
    postedBy: 'പോസ്റ്റ് ചെയ്തത്', description: 'വിവരണം', noReviews: 'അഭിപ്രായങ്ങളൊന്നുമില്ല',
    skills: 'നൈപുണ്യങ്ങൾ', contactWhatsapp: '💬 WhatsApp-ൽ ബന്ധപ്പെടുക',
    expressInterest: '👋 താൽപ്പര്യം അറിയിക്കുക', interestExpressed: '✅ താൽപ്പര്യം അറിയിച്ചു',
    leaveReview: '⭐ അഭിപ്രായം നൽകുക', shareExperience: 'നിങ്ങളുടെ അനുഭവം പങ്കിടുക...',
    submitReview: 'അഭിപ്രായം സമർപ്പിക്കുക', submitting: 'സമർപ്പിക്കുന്നു...',
    signInFirst: 'ആദ്യം സൈൻ ഇൻ ചെയ്യുക.',
    interestToast: 'താൽപ്പര്യം അറിയിച്ചു! പോസ്റ്റർ നിങ്ങളുടെ പ്രൊഫൈൽ കാണും.',
    reviewSuccess: 'അഭിപ്രായം സമർപ്പിച്ചു!', reviewError: 'അഭിപ്രായം സമർപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു.',
    reviews: 'അഭിപ്രായങ്ങൾ', interested: 'താൽപ്പര്യം',
    jobNotFound: 'ജോലി കണ്ടെത്തിയില്ല.', loading: 'ലോഡ് ചെയ്യുന്നു...',
    locationNotSet: '📍 സ്ഥലം നൽകിയിട്ടില്ല',
    editProfile: '✏️ എഡിറ്റ്', cancelEdit: 'റദ്ദാക്കുക',
    areaLocalityLabel: 'പ്രദേശം / ലൊക്കാലിറ്റി', phoneLabel: 'ഫോൺ (WhatsApp ബന്ധപ്പെടാൻ)',
    skillsOfferedLabel: 'ഞാൻ നൽകുന്ന നൈപുണ്യങ്ങൾ (കോമയാൽ വേർതിരിക്കുക)',
    skillsOfferedPlaceholder: 'ഉദാ: പ്ലംബിംഗ്, ഗിറ്റാർ, പാചകം',
    skillsNeededLabel: 'ഞാൻ പഠിക്കാൻ ആഗ്രഹിക്കുന്ന നൈപുണ്യങ്ങൾ (കോമയാൽ വേർതിരിക്കുക)',
    skillsNeededPlaceholder: 'ഉദാ: ഡ്രൈവിംഗ്, തയ്യൽ',
    saveProfile: 'പ്രൊഫൈൽ സേവ് ചെയ്യുക', saving: 'സേവ് ചെയ്യുന്നു...',
    profileSaved: 'പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്തു!', profileError: 'സേവ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.',
    myPosts: 'എന്റെ പോസ്റ്റുകൾ', noPostsYet: 'നിങ്ങൾ ഇതുവരെ ഒന്നും പോസ്റ്റ് ചെയ്തിട്ടില്ല.',
    postAJob: 'ഒരു ജോലി പോസ്റ്റ് ചെയ്യുക →', loadingProfile: 'പ്രൊഫൈൽ ലോഡ് ചെയ്യുന്നു...', needsLabel: 'ആവശ്യം:',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  const toggleLang = () => setLang((l) => (l === 'en' ? 'ml' : 'en'))
  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
